export const FETCH_GUARDERIAS_REQUEST = 'FETCH_GUARDERIAS_REQUEST'
export const FETCH_GUARDERIAS_SUCCESS = 'FETCH_GUARDERIAS_SUCCESS'
export const FETCH_GUARDERIAS_FAILURE = 'FETCH_GUARDERIAS_FAILURE'