export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

/* export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST'
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS'
export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE' */