export const FETCH_VETERINARIAS_REQUEST = 'FETCH_VETERINARIAS_REQUEST'
export const FETCH_VETERINARIAS_SUCCESS = 'FETCH_VETERINARIAS_SUCCESS'
export const FETCH_VETERINARIAS_FAILURE = 'FETCH_VETERINARIAS_FAILURE'