export const LINK_HOME = '/'
export const LINK_INGRESAR = '/ingresar'
export const LINK_REGISTRARSE = '/registrarse'
export const LINK_PASEOS = '/paseos'
export const LINK_VETERINARIAS = '/veterinarias'
export const LINK_GUARDERIAS = '/guarderias'
export const LINK_SALTOS = '/saltos'
export const LINK_PERFIL = '/perfil'