export const LINK_HOME = '/'
export const LINK_INGRESAR = '/ingresar'
export const LINK_REGISTRARSE = '/registrarse'
export const LINK_PASEOS = '/paseos'
export const LINK_VETERINARIA = '/veterinaria'
export const LINK_GUARDERIA = '/guarderia'
export const LINK_SALTOS = '/saltos'